

FROM python:3.11-slim

WORKDIR /app

COPY ./app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /app

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "127.0.0.1", "--port", "5000"]
