FROM python:3.11-slim

WORKDIR /app

COPY ./classify/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./classify /app

ENV PYTHONPATH=/app

EXPOSE 8080

CMD ["uvicorn", "main-api:app", "--host", "0.0.0.0", "--port", "8080"]
