FROM python:3.11-slim

WORKDIR /app

COPY ./classify/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./classify /app

EXPOSE 8000

CMD ["uvicorn", "classify:app", "--host", "127.0.0.1", "--port", "8000"]
