FROM python:3.11-slim

WORKDIR /app

COPY ./api_service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./api_service /app

EXPOSE 8000

CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
